################################################################################## Version: @version@
# +--------------▄▄▄-- ‚——. -▄--▄-▄--▄-▄-▄▄▄▄▄---------------------------------------------------+ #
# |              █▄▄▀ (“‡‡”) █▄▄▀ █▄▄▀ █   █         Support available at: discord.gg/mTaHuK6BVa | #
# |              █▄▄█  \__/  █  █ █  █ █   █                    ‚-.                              | #
# |         —————————————————————————————————————————————————— ((_)) ——————————————————          | #
# |                                                             ‘-’                              | #
# |         .|'''.|  |''||''|     |     '||''|.    ..|'''.|      |     |''||''| '||''''|         | #
# |         ||..  '     ||       |||     ||   ||  .|'     '     |||       ||     ||  .           | #
# |          ''|||.     ||      |  ||    ||''|'   ||    ....   |  ||      ||     ||''|           | #
# |        .     '||    ||     .''''|.   ||   |.  '|.    ||   ;’   |.     ||     ||              | #
# |         '....|'    .||.   .|.  .||. .||.  '|'  ''|...'|  .|.  .||.   .||.   .||.....|        | #
# +----------------------------------------------------------------------------------------------+ #
# |                        https://spigotmc.org/resources/stargate.87978/                        | #
# +----------------------------------------------+-----------------------------------------------+ #
# |      Documentation: https://git.io/Jc6jZ     |       Bug Reports: https://git.io/Jc6jW       | #
# +----------------------------------------------+-----------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                      General Preferences                                     | #
# +----------------------------------------------------------------------------------------------+ #

# What language will stargate use when communicating with your users?
# Supported values: [en, de, es, fr, hu, it, nl, pt, ru, sv, zh-CN, & zh-HK]
# 
# If SG isn't yet available in your language, please consider a PR: https://git.io/JcixA 
# For more information on language codes, see ISO 639-1: https://git.io/JcwaI
lang: en

# Are you connected to a bungee-compatible proxy?
# Set this value to true if you intend on building gates with the 'u' flag.
enableBungee: false

# What network will be used when none has been specified? (Max length 12 characters)
#
# Note that this primarily applies to users with the stargate.create.network node.
# Generally, that node is given to staff (we recommend stargate.create.personal for users).
default-gate-network: central

# +----------------------------------------------------------------------------------------------+ #
# |                                        Gate Behaviour                                        | #
# +----------------------------------------------------------------------------------------------+ #

# What is the maximum number of gates a single network may contain? (0 for unlimited)
maxgates: 0

# Will vehicles and their passengers be able to travel through StarGate portals?
#  [minecarts, boats, & saddled mobs = vehicles | players & mobs = passengers]
# 
# …««»»…  This feature is partially incompatible with MineCraft 1.9+.
# “NOTE”  There is a planned fix for this in the upcoming SG rewrite (for MC 1.18+).
handleVehicles: true

# Will the server reverify all existing portals on startup?
#
# This checks that the expected gates are both present and using a valid layout.
# Designed to catch .gate file modifications, world changes, and terrain regeneration.
#
# …««»»…  Should be set to true in conjuction with ignoreEntrance; Players without
# “NOTE”  perms, block updates, and snowmen would otherwise be able to destroy portals on restart
verifyPortals: false

# Should the verifyPortals check ignore entrance materials?
# I.e. will a gate validate if its portal-open material isn't present
#
# When disabled, this setting makes gate validation more comprehensive,
# traversable blocks will not be able to overwrite existing blocks.
ignoreEntrance: false

# SG protects gate 𝑓𝑟𝑎𝑚𝑒 materials; should it also protect gate 𝑡𝑟𝑎𝑣𝑒𝑟𝑠𝑎𝑏𝑙𝑒 (open/closed) materials?
# ex. in nether.gate, should nether_portal be protected?
#
# …««»»…  This feature can be somewhat resource intensive when active!
# “NOTE”  Only enable this if you use breakable 𝑡𝑟𝑎𝑣𝑒𝑟𝑠𝑎𝑏𝑙𝑒 materials.
protectEntrance: false

# Can StarGates be broken via an explosion?
#  [tnt, creepers, etc.]
destroyexplosion: false

# +----------------------------------------------------------------------------------------------+ #
# |                                            Economy                                           | #
# +----------------------------------------------------------------------------------------------+ #

# Will StarGate interact with your server's economy?
#
# …««»»…  For these features, StarGate depends on the Vault plugin.
# “NOTE”  https://www.spigotmc.org/resources/vault.34315/
useeconomy: false

# How much will be deducted from players' accounts when creating a new gate?
createcost: 0

# How much will be deducted from players' accounts when destroying an existing gate?
destroycost: 0

# How much will be deducted from players' accounts when using a stargate to teleport?
# This does not apply to stargates with the 'f' flag.
usecost: 0

# Will fees collected for ‘usecost’ be paid to whomever created (owns) the applicable stargate?
# If false, collected funds will be deleted.
toowner: false

# Will ‘createcost’ still be charged if the new gate's destination is a gate with the 'f' flag?
# Note that this only applies to fixed gates.
chargefreedestination: true

# +----------------------------------------------------------------------------------------------+ #
# |                                       Aesthetic Tweaks                                       | #
# +----------------------------------------------------------------------------------------------+ #

# What colour will StarGate use for all text when formatting gate signs?
# Note that players can override this with DYE and/or GLOW_INK_SAC
#
# All colour names should follow this format:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Color.html#field.summary
signColor: BLACK

# Will free gates show up as green when scrolling throught portals in a networked portal
freegatesgreen: false

# For networked gates, are destinations listed alphabetically instead of chronologically?
# (This applies to all non-fixed and non-random gates).
sortLists: false

# Will networked portals remember the last portal it connected to and show this as initial destination?
#
# …««»»…  This feature does not appear to be working at the moment.
# “NOTE”  There is a planned fix for this in the upcoming SG rewrite (for MC 1.18+).
destMemory: false

# +----------------------------------------------------------------------------------------------+ #
# |                                           Technical                                          | #
# +----------------------------------------------------------------------------------------------+ #

# |                                       [ Compatibility ]                                      | #
# |__      These settings are provided to improve SG 10's interactions with other plugins.     __| #

# Currently, all valid gates, their details, and their owners, are stored in a flatfile database
# Where should that flatfile be stored?
#
# This option is provided as a patch to allow data to be imported from some older forks.
portal-folder: plugins/Stargate/portals/

# Currently, on startup, a folder is checked for gate layouts stored as ‘.gate’ files.
# Where is that folder?
#
# This option is provided as a patch to allow data to be imported from some older forks.
gate-folder: plugins/Stargate/gates/

# |                                           [ Debug ]                                          | #
# |__     These settings are provided to help developers diagnose issues with this plugin.     __| #

# Should SG spam console with A LOT of technical information?
# This includes checks, events, etc.
debug: false

# Should SG spam console with A LOT of permission-based information?
# This visualises how stargate determines what players can do.
#
# Note that (regardless of this setting), permdebug is always hidden when ‘debug’ is false.
permdebug: false

# An internal value used by the plugin to determine how old your config is.
# Please do not change this.
configVersion: 2
