# Stargate Configuration File  v. @version@
preferences:
  language: en
  usingBungee: true
  defaultGateNetwork: central
behaviour:
  gateLimit: 0
  handleVehicles: true
  checkPortalValidity: false
  checkTraversables: false
  protectEntrance: false
  destroyOnExplosion: false
economy:
  useEconomy: false
  taxDestination: 
  upkeepCost: 0
  creationCost: 0
  destroyCost: 0
  useCost: 0
  gateOwnerRevenue: false
  chargeFreeDestination: true
tweaks:
  defaultSignColour: BLACK
  highlightFreeGates: false
  alphabeticNetworks: false
  rememberLastDestination: false
technical:
  debug:
    # Lowest level of visibility for the plugin
    debug-level: INFO
    
configVersion: 5