# Stargate Configuration File  v. @version@
# TODO This needs to be replaced with the config outlined in Discussion Two.
preferences:
# TODO Update localisation prompts.
  language: en
  usingBungee: true
  defaultGateNetwork: central
behaviour:
  gateLimit: 0
  handleVehicles: true
  checkPortalValidity: false
  checkTraversables: false
  protectEntrance: false
  destroyOnExplosion: false
economy:
  useEconomy: false
  taxDestination: 
  upkeepCost: 0
  creationCost: 0
  destroyCost: 0
  useCost: 0
  gateOwnerRevenue: false
  chargeFreeDestination: true
tweaks:
  defaultSignColour: BLACK
  highlightFreeGates: false
  alphabeticNetworks: false
  rememberLastDestination: false
technical:
  # Name of internal stargate storage
  database: stargate
  
  # Settings for bungee portal storage. Note that this has to be the same for all stargate-bungeeinstances.
  bungee:
    # current tested drivers[mysql,mariadb,sqlite]
    # sqlite not recomended for non local server networks or large networks
    driver: sqlite
    database: stargateBungee
    port:
    # TODO This should be reset to a default value!
    address: C:\Users\46737\Desktop\Stupid location
  debug:
    # Lowest level of visibility for the plugin
    debug-level: INFO
    debug-targets: []
    
configVersion: 5