name: Stargate
main: net.TheDgtl.Stargate.Stargate
version: @version@
description: Stargate mod for Bukkit
authors: [Dinnerbone, Drakia, PseudoKnight, Thorin]
website: https://discord.gg/mTaHuK6BVa
api-version: 1.15
softdepend: [Vault]
commands:
  sg:
    description: Used to reload the plugin. Console use only.
    usage: /<command> reload - Used to reload the plugin. Console use only.
permissions:
  sg:
    children:
    
      sg.info:
        default: true
        description: Group of nodes displaying info about the plugin (part of the /sg command).
        children:
          sg.info.version:
            description: Displays the plugin's version in chat. (/sg version)
          sg.info.help:
            description: Links to the plugin's documentation in chat. (/sg help)
            
      sg.admin:
        description: Group of nodes generally used by staff and admins.
        default: op
        children: 
          sg.admin.reload:
            description: Reloads the plugin's configuration (/sg reload)
          sg.admin.bypass:
            description: Bypasses various portal factors
            children:
              sg.admin.bypass.private:
                description: Can see and use P gates
              sg.admin.bypass.hidden:
                description: Can see H gates
              sg.admin.bypass.cost:
                description: Bypass vault costs associated with portals
                children:
                  sg.admin.bypass.cost.destroy: 
                    description: Bypass the cost associated with destroying a portal
                  sg.admin.bypass.cost.create:
                    description: Bypass the cost associated with creating a portal
                  sg.admin.bypass.cost.use:
                    description: Bypass the cost associated with creating a portal
    
      sg.use:
        default: true
        description: Can use any portal (can not see H gates, can not use other users' P gates).
        children:
          sg.use.follow:
            description: Allow entering gates opened by another player
          sg.use.world:
            description: Allows players to use portals connecting to any dimension.
          sg.use.network:
            description: Allows players to use portals on any network.
            children: 
              sg.use.network.custom:
                description: Use portal on any custom network
              sg.use.network.personal:
                description: Can use portals on their personal network.
              sg.use.network.default:
                description: Can use portals on the default network (central)
          sg.use.type:
            description: Can use all portals, regardless of flag type.
            children:
              sg.use.type.a:
                description: Can use always-on gates.
              sg.use.type.b:
                description: Can use backwards-facing gates.
              sg.use.type.f:
                description: Can use free gates.
              sg.use.type.h:
                description: Can use hidden gates.
              sg.use.type.i:
                description: Can use modern interserver gates.
              sg.use.type.n:
                description: Can use hidden-network gates.
#             sg.use.type.of:
#               description: Can use toggle gates.
              sg.use.type.p:
                description: Can use private gates.
              sg.use.type.r:
                description: Can use random gates.
              sg.use.type.s:
                description: Can use showing gates.
#             sg.use.type.t:
#               description: Can use terminal gates.
              sg.use.type.u:
                description: Can use legacy bungee gates.
#             sg.use.type.v:
#               description: Can use gates with invisible signs.
              sg.use.type.fixed:
                description: Can use fixed gates
              sg.use.type.non-fixed:
                description: Can use non-fixed gates
          sg.use.design:
            description: Can use any portal, regardless of the portal's design (gatefile).
          
      sg.create:
        default: op
        description: Allows creating any portal
        children:
          sg.create.world:
            default: true
            description: Allows players to create portals in any dimension.
          sg.create.network:
            description: Allows players to create portals on any network.
            children:
              sg.create.network.custom:
                description: Create portal on any custom network
              sg.create.network.personal:
                default: true
                description: Can create portals on their personal network.
                #TODO: Meta for personal network limits. Requires vault. See discussion four.
              sg.create.network.default:
                description: Can create portals on the default network (central)
          sg.create.type:
            description: Can use all flags when creating portals
            children:
              sg.create.type.a:
                description: Can create gates with the always-on flag.
              sg.create.type.b:
                description: Can create gates with the backwards-facing flag.
              sg.create.type.f:
                description: Can create gates with the free flag.
              sg.create.type.h:
                description: Can create gates with the hidden flag.
              sg.create.type.i:
                description: Can create gates with the modern interserver flag.
              sg.create.type.n:
                description: Can create gates with the hidden-network flag.
#             sg.create.type.o:
#               description: Can create gates with the toggle flag.
              sg.create.type.p:
                description: Can create gates with the private flag.
              sg.create.type.r:
                description: Can create gates with the random flag.
              sg.create.type.s:
                description: Can create gates with the showing flag.
#             sg.create.type.t:
#               description: Can create terminal portals (be they in the terminal, or connecting to it)
#               children:
#                 sg.create.type.t.new:
#                   description: Can create (sell) a new terminal gate on any network they have access to.
#                   children:
#                     sg.create.type.t.new.default:
#                       description: Can create (sell) a new terminal gate on the default terminal network.
#                 sg.create.type.t.connect:
#                   description: Can create a gate connecting to any existing, available (for sale) terminal gate. !!(BYPASSES stargate.create.network)!!
#                   children:
#                     sg.create.type.t.connect.default:
#                       description: Can create a gate connecting to any existing, available (for sale) terminal gate on the default network.              
              sg.create.type.u:
                description: Can create gates with the legacy bungee flag.
#             sg.create.type.v:
#               description: Can create gates with invisible signs.
          sg.create.design:
            description: Can create any portal, regardless of the design (gatefile)
            children:
              sg.create.design.nether.gate: true
              sg.create.design.water.gate: true
              sg.create.design.wool.gate: true
              
            
      sg.destroy:
        description: Can destroy any portal
        default: op
        children: 
          sg.destroy.world:
            description: Can destroy portals, regardless of dimension
            default: true
          sg.destroy.network:
            description: Can destroy portals, regardless of network
            children:
              sg.destroy.network.personal:
                description: Can destroy any portals on your personal network.
              sg.destroy.network.default:
                description: Can destroy any portals on the default network. (central)
              sg.destroy.network.custom:
                description: Can destroy any portals on any custom network.
          sg.destroy.type: 
            description: Can destroy portals, regardless of type.
            children:
              sg.destroy.type.a:
                description: Can destroy always-on gates.
              sg.destroy.type.b:
                description: Can destroy backwards-facing gates.
              sg.destroy.type.f:
                description: Can destroy free gates.
              sg.destroy.type.h:
                description: Can destroy hidden gates.
              sg.destroy.type.i:
                description: Can destroy modern interserver gates.
              sg.destroy.type.n:
                description: Can destroy hidden-network gates.
#             sg.destroy.type.o:
#               description: Can destroy toggle gates.
              sg.destroy.type.p:
                description: Can destroy private gates.
              sg.destroy.type.r:
                description: Can destroy random gates.
              sg.destroy.type.s:
                description: Can destroy showing gates.
#             sg.destroy.type.t:
#               description: Can destroy terminal gates.
              sg.destroy.type.u:
                description: Can destroy legacy bungee gates.
#             sg.destroy.type.v:
#               description: Can destroy gates with invisible signs.
          sg.destroy.design:
            description: Can destroy portals, regardless of design (gatefile).
            
      sg.preset:
        description: Premade groupings for convenience.
        default: false
        children:
          sg.preset.user:
            description: A permission set intended to be given to players who will be using -- but not making -- stargates.
            children:
              sg.info: true
              sg.use: true
          sg.preset.gatemaker:
            description: A permission set intended to be given to players who will be making basic stargates for personal usage.
            children:
              sg.create.network.personal: true
              sg.destroy.network.personal: true
              sg.create.type.h: true
              sg.create.type.p: true
              sg.destroy.type.h: true
              sg.destroy.type.p: true
              sg.create.design: true
              sg.destroy.design: true
#             sg.create.type.o: true
#         sg.preset.terminaluser:
#           description: A permission set intended to be given to players who will be making basic stargates for personal usage.
#           children:
#             sg.preset.gatemaker: true
#             sg.create.type.t.connect.default: true
#         sg.preset.terminaluser:
#           description: A permission set intended to be given to any staff who will be involved in making / administrating a terminal system in spawn.
#           children:
#             sg.preset.terminaluser: true
#             sg.preset.type.t.new.default: true
          sg.preset.builder:
            description: A set of permissions intended to be given to staff who will be making advanced stargates for server usage.
            children:
              sg.preset.gatemaker: true
              sg.create.network.default: true
              sg.create.type.a: true
              sg.create.type.b: true
              sg.create.type.n: true
              sg.create.type.s: true
              sg.create.type.u: true
              sg.create.type.i: true
#             sg.create.type.v: true
          sg.preset.moderator:
            description: A set of permissions intended to be given to staff who will be moderating stargate usage amongst players.
            children:
              sg.preset.builder: true
              sg.create.type.f: true
              sg.create.type.r: true
              sg.destroy.network: true
              sg.create.network: true
              sg.admin.bypass: true
          sg.preset.admin:
            description: A set of permissions intended to be given to admins tasked with configuring stargate and its permissions.
            children:
              sg.preset.moderator: true
              sg.create: true
              sg.admin: true
