version: 2.1
jobs:
  build-and-test:
    docker:
      - image: debian:12.4

      - image: cimg/maven:1.4.1
            
      - image: cimg/mariadb:11.2.1
        environment:
          MARIADB_DATABASE: stargate
          MARIADB_USER: root
          MARIADB_PASSWORD: password

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/my-project/stargate/core

    steps:
      - checkout

      - run:
          name: Debug and Environment
          command: |
            echo 127.0.0.1 devhost | echo ls | tee -a /etc/hosts
            mkdir -p ~/my-projects/stargate/core
            cd ~/my-projects/stargate/core
            
      - run:
          name: Install Stuff
          command: |
            apt-get update && apt-get install -y mariadb-client
            apt-get install -y git
            apt-get install -y maven
            
      - run:
          name: Clone Repository
          command: |
            git clone https://github.com/stargate-rewritten/Stargate-Bukkit.git
            cd ~/my-projects/stargate/core/Stargate-Bukkit
            git checkout nightly
      
      - restore_cache:
          keys:
            - maven-data
      
      - run:
          name: Populate Secrets File
          command: |
            touch ~/my-projects/stargate/core/Stargate-Bukkit/src/test/resources/mysql_credentials.secret
            echo MYSQL_DB_PASSWORD=password >> ~/my-projects/stargate/core/Stargate-Bukkit/src/test/resources/mysql_credentials.secret
            echo MYSQL_DB_USER=root >> ~/my-projects/stargate/core/Stargate-Bukkit/src/test/resources/mysql_credentials.secret
            
      - run:
          name: Attempt to Build
          command: |
            mvn clean install

      - save_cache:
          key: maven-data
          paths:
            - ~/my-projects/stargate/core/Stargate-Bukkit/target

      - run:
          name: Move valid files
          command: |
            mkdir ~/my-projects/stargate/core/Stargate-Bukkit/target/export
            cd ~/my-projects/stargate/core/Stargate-Bukkit/target
            mv Stargate-*.jar export

      - store_artifacts:
          path: ~/my-projects/stargate/core/Stargate-Bukkit/target/export
          destination: build

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/